<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="5" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-17T20:14:36 IST" name="Suite" finished-at="2025-07-17T20:15:11 IST" duration-ms="34250">
    <groups>
      <group name="checking">
        <method signature="SubmitOrdersTest.submitOrders(java.util.HashMap)[pri:0, instance:seleniumFrameworkDesign.SubmitOrdersTest@5a59ca5e]" name="submitOrders" class="seleniumFrameworkDesign.SubmitOrdersTest"/>
      </group> <!-- checking -->
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.errormessage()[pri:0, instance:seleniumFrameworkDesign.ErrorValidationTest@f68f0dc]" name="errormessage" class="seleniumFrameworkDesign.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2025-07-17T20:14:36 IST" name="submit order test" finished-at="2025-07-17T20:14:59 IST" duration-ms="22495">
      <class name="seleniumFrameworkDesign.SubmitOrdersTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:seleniumFrameworkDesign.SubmitOrdersTest@5a59ca5e]" started-at="2025-07-17T20:14:37 IST" name="launchApplication" finished-at="2025-07-17T20:14:42 IST" duration-ms="5038" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrders(java.util.HashMap)[pri:0, instance:seleniumFrameworkDesign.SubmitOrdersTest@5a59ca5e]" started-at="2025-07-17T20:14:42 IST" name="submitOrders" data-provider="getData" finished-at="2025-07-17T20:14:46 IST" duration-ms="4173" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Ganesh143, product=ZARA COAT 3, email=ramaganesh209@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrders -->
        <test-method is-config="true" signature="closingApplication()[pri:0, instance:seleniumFrameworkDesign.SubmitOrdersTest@5a59ca5e]" started-at="2025-07-17T20:14:46 IST" name="closingApplication" finished-at="2025-07-17T20:14:46 IST" duration-ms="269" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closingApplication -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:seleniumFrameworkDesign.SubmitOrdersTest@5a59ca5e]" started-at="2025-07-17T20:14:46 IST" name="launchApplication" finished-at="2025-07-17T20:14:49 IST" duration-ms="2778" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrders(java.util.HashMap)[pri:0, instance:seleniumFrameworkDesign.SubmitOrdersTest@5a59ca5e]" started-at="2025-07-17T20:14:49 IST" name="submitOrders" data-provider="getData" finished-at="2025-07-17T20:14:53 IST" duration-ms="3974" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Ganesh143, product=ADIDAS ORIGINAL, email=ramaganesh209@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrders -->
        <test-method is-config="true" signature="closingApplication()[pri:0, instance:seleniumFrameworkDesign.SubmitOrdersTest@5a59ca5e]" started-at="2025-07-17T20:14:53 IST" name="closingApplication" finished-at="2025-07-17T20:14:53 IST" duration-ms="258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closingApplication -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:seleniumFrameworkDesign.SubmitOrdersTest@5a59ca5e]" started-at="2025-07-17T20:14:53 IST" name="launchApplication" finished-at="2025-07-17T20:14:57 IST" duration-ms="3785" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistoreTest()[pri:0, instance:seleniumFrameworkDesign.SubmitOrdersTest@5a59ca5e]" started-at="2025-07-17T20:14:57 IST" name="OrderHistoreTest" finished-at="2025-07-17T20:14:59 IST" depends-on-methods="seleniumFrameworkDesign.SubmitOrdersTest.submitOrders" duration-ms="1569" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoreTest -->
        <test-method is-config="true" signature="closingApplication()[pri:0, instance:seleniumFrameworkDesign.SubmitOrdersTest@5a59ca5e]" started-at="2025-07-17T20:14:59 IST" name="closingApplication" finished-at="2025-07-17T20:14:59 IST" duration-ms="213" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closingApplication -->
      </class> <!-- seleniumFrameworkDesign.SubmitOrdersTest -->
    </test> <!-- submit order test -->
    <test started-at="2025-07-17T20:15:00 IST" name="error validation test" finished-at="2025-07-17T20:15:11 IST" duration-ms="10707">
      <class name="seleniumFrameworkDesign.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:seleniumFrameworkDesign.ErrorValidationTest@f68f0dc]" started-at="2025-07-17T20:15:00 IST" name="launchApplication" finished-at="2025-07-17T20:15:04 IST" duration-ms="4159" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="errormessage()[pri:0, instance:seleniumFrameworkDesign.ErrorValidationTest@f68f0dc]" started-at="2025-07-17T20:15:04 IST" name="errormessage" finished-at="2025-07-17T20:15:05 IST" duration-ms="1000" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or passlkjhword.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or passlkjhword.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at seleniumFrameworkDesign.ErrorValidationTest.errormessage(ErrorValidationTest.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errormessage -->
        <test-method is-config="true" signature="closingApplication()[pri:0, instance:seleniumFrameworkDesign.ErrorValidationTest@f68f0dc]" started-at="2025-07-17T20:15:05 IST" name="closingApplication" finished-at="2025-07-17T20:15:05 IST" duration-ms="282" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closingApplication -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:seleniumFrameworkDesign.ErrorValidationTest@f68f0dc]" started-at="2025-07-17T20:15:05 IST" name="launchApplication" finished-at="2025-07-17T20:15:09 IST" duration-ms="3686" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="errormessage()[pri:0, instance:seleniumFrameworkDesign.ErrorValidationTest@f68f0dc]" started-at="2025-07-17T20:15:09 IST" name="errormessage" finished-at="2025-07-17T20:15:10 IST" duration-ms="771" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or passlkjhword.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or passlkjhword.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at seleniumFrameworkDesign.ErrorValidationTest.errormessage(ErrorValidationTest.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errormessage -->
        <test-method is-config="true" signature="closingApplication()[pri:0, instance:seleniumFrameworkDesign.ErrorValidationTest@f68f0dc]" started-at="2025-07-17T20:15:10 IST" name="closingApplication" finished-at="2025-07-17T20:15:11 IST" duration-ms="204" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closingApplication -->
      </class> <!-- seleniumFrameworkDesign.ErrorValidationTest -->
    </test> <!-- error validation test -->
  </suite> <!-- Suite -->
</testng-results>
